#!/bin/bash

if [[ $EUID -ne 0 ]]; then

	   echo This script must be run as root

	      exit 0;

fi




if [ -z $1 ]

then

	        echo needs input

		        exit 0;

fi

if [ "$1" == "-t" ];then

	while getopts t: option; do

		case ${option}

		in

			t) TYPE=${OPTARG};;

		esac

	done

	if [ "$TYPE" == "MX" ]; then

		ZONE=echo $5

		echo "@		     IN	      MX	10 $3" >> /etc/bind/db.$ZONE

		echo "$3	     IN	       A	$4" >> /etc/bind/db.$ZONE

		i=$(grep Serial /etc/bind/db.$ZONE | cut -d' ' -f1)

		

		j=$((i+1))

		

		sed -i "s/$i ; Serial/$j ; Serial/" /etc/bind/db.$ZONE

		

	elif [ "$TYPE" = "CNAME" ]

	then

		ZONE=$4

		echo "$3	    IN	     CNAME	$4" >> /etc/bind/db.$ZONE

		i=$(grep Serial /etc/bind/db.$ZONE | cut -d' ' -f1)

		

		j=$((i+1))

		

		sed -i "s/$i ; Serial/$j ; Serial/" /etc/bind/db.$ZONE

		

	elif [ "$TYPE" == "A" ]

	then

		ZONE=$5

		echo "$3		IN	A	$4" >> /etc/bind/db.$ZONE

		i=$(grep Serial /etc/bind/db.$ZONE | cut -d' ' -f1)

		

		j=$((i+1))

		

		sed -i "s/$i ; Serial/$j ; Serial/" /etc/bind/db.$ZONE		

	else

		echo no valid dns record

		exit 0;

	fi

else

	ZONE=$3

	echo "$1		IN	A	$2" >> /etc/bind/zones/zone.$ZONE

	i=$(grep Serial /etc/bind/db.$ZONE | cut -d' ' -f1)

	

	j=$((i+1))

	

	sed -i "s/$i ; Serial/$j ; Serial/" /etc/bind/db.$ZONE

fi




rndc reload
