#!/bin/bash

if [[ $EUID -ne 0 ]]; then

	   echo This script must be run as root

	      exit 0;

fi




if [ -z $1 ]

then

	echo needs a subdomain

	exit 0;

fi




cat <<EOF>> /etc/bind/named.conf.mrt-zones

zone "$1.sander-doggen.sb.uclllabs.be"  {

        type master;

        file "/etc/bind/db.$1.sander-doggen.sb.uclllabs.be";

		



};

EOF



cat <<EOF>> /etc/bind/db.$1.sander-doggen.sb.uclllabs.be

;

; BIND data file for local loopback interface

;

\$TTL    600

@       IN      SOA     $1.sander-doggen.sb.uclllabs.be. admin.sander-doggen.sb.uclllabs.be. (

5 ; Serial

                             600         ; Refresh

                             600        ; Retry

                             600        ; Expire

                             600 )       ; Negative Cache TTL

;

       IN      NS     ns.sander-doggen.sb.uclllabs.be.


ns	IN	A	193.191.177.214



EOF

echo -e "$1	IN	NS	ns.sander-doggen.sb.uclllabs.be." >> /etc/bind/forward.sander-doggen.sb.uclllabs.be



i=$(grep Serial /etc/bind/forward.sander-doggen.sb.uclllabs.be|tr -s [:blank:] | cut -d ' ' -f 2)

echo $i

j=$((i+1))

echo $j

sed -i "s/.*Serial.*/\t\t     $j ;Serial/g" /etc/bind/forward.sander-doggen.sb.uclllabs.be

rndc reload

systemctl restart bind9

